
import java.awt.Button;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sala305b
 */
public class Calcula extends javax.swing.JFrame {

//    private JTextField nro1;
//    private JTextField nro2;
    public Calcula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nro1 = new javax.swing.JTextField();
        Nro2 = new javax.swing.JTextField();
        btnSomar = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnVerPar = new javax.swing.JButton();
        btnVerDivisivel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("NUMERO 01 :");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("NUMERO 02 :");

        Nro1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nro1.setName("nro1"); // NOI18N

        Nro2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Nro2.setName("nro2"); // NOI18N
        Nro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nro2ActionPerformed(evt);
            }
        });

        btnSomar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSomar.setLabel("SOMAR");
        btnSomar.setMaximumSize(new java.awt.Dimension(100, 25));
        btnSomar.setMinimumSize(new java.awt.Dimension(100, 25));
        btnSomar.setName("btnSomar"); // NOI18N
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });

        btnSubtrair.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSubtrair.setLabel("SUBTRAIR");
        btnSubtrair.setMaximumSize(new java.awt.Dimension(100, 25));
        btnSubtrair.setMinimumSize(new java.awt.Dimension(100, 25));
        btnSubtrair.setName("btnSubtrair"); // NOI18N
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });

        btnMultiplicar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMultiplicar.setLabel("MULTIPLICAR");
        btnMultiplicar.setMaximumSize(new java.awt.Dimension(100, 25));
        btnMultiplicar.setMinimumSize(new java.awt.Dimension(100, 25));
        btnMultiplicar.setName("btnMultiplicar"); // NOI18N
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnDividir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnDividir.setLabel("DIVIDIR");
        btnDividir.setMaximumSize(new java.awt.Dimension(100, 25));
        btnDividir.setMinimumSize(new java.awt.Dimension(100, 25));
        btnDividir.setName("btnDividir"); // NOI18N
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnVerPar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVerPar.setLabel("VER PAR");
        btnVerPar.setMaximumSize(new java.awt.Dimension(100, 25));
        btnVerPar.setMinimumSize(new java.awt.Dimension(100, 25));
        btnVerPar.setName("btnVerPar"); // NOI18N
        btnVerPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerParActionPerformed(evt);
            }
        });

        btnVerDivisivel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnVerDivisivel.setLabel("VER DIVISIVEL");
        btnVerDivisivel.setMaximumSize(new java.awt.Dimension(100, 25));
        btnVerDivisivel.setMinimumSize(new java.awt.Dimension(100, 25));
        btnVerDivisivel.setName("btnDivisivel"); // NOI18N
        btnVerDivisivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDivisivelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("RESULTADO :");

        Result.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Result.setName("Result"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerPar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVerDivisivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nro2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(Nro1))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nro1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nro2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerDivisivel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerPar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Result, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nro2ActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed

        double num1 = Double.parseDouble(Nro1.getText());
        double num2 = Double.parseDouble(Nro2.getText());

        Numero n = new Numero();
        Double total = n.somar(num1, num2);

        Result.setText(String.valueOf(total));


    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        double num1 = Double.parseDouble(Nro1.getText());
        double num2 = Double.parseDouble(Nro2.getText());

        Numero n = new Numero();
        double total = n.subtrair(num1, num2);

        Result.setText(String.valueOf(total));
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        double num1 = Double.parseDouble(Nro1.getText());
        double num2 = Double.parseDouble(Nro2.getText());

        Numero n = new Numero();
        double total = n.multiplicar(num1, num2);

        Result.setText(String.valueOf(total));
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        double num1 = Double.parseDouble(Nro1.getText());
        double num2 = Double.parseDouble(Nro2.getText());

        Numero n = new Numero();
        double total = n.dividir(num1, num2);

        Result.setText(String.valueOf(total));
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnVerParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerParActionPerformed
        double num1 = Double.parseDouble(Nro1.getText());
        double num2 = Double.parseDouble(Nro2.getText());

        Numero n = new Numero();
        String total = n.verPar(num1, num2);

        Result.setText(total);


    }//GEN-LAST:event_btnVerParActionPerformed

    private void btnVerDivisivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDivisivelActionPerformed
        double num1 = Double.parseDouble(Nro1.getText());
        double num2 = Double.parseDouble(Nro2.getText());
        String msg = "";
        Numero n = new Numero();
        Boolean ehDiv = n.verDivisivel(num1, num2);

        if (ehDiv) {
            msg = num1 + "é divisível por " + num2;
            JOptionPane.showMessageDialog(rootPane, msg);
        } else {
            msg = num1 + " não é divisível por " + num2;
            JOptionPane.showMessageDialog(rootPane, msg);
        }

        Result.setText(msg);
    }//GEN-LAST:event_btnVerDivisivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nro1;
    private javax.swing.JTextField Nro2;
    private javax.swing.JTextField Result;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JButton btnVerDivisivel;
    private javax.swing.JButton btnVerPar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
